finalproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from django.views.static import serve
from django.views.generic.base import RedirectView

from map import views
from map.views import *

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('map.urls')),
    url(r'^map/$', map, name='map'),
    url(r'^map/m(?P<id>[0-9]+)/$', boothmap, name='boothmap'),
    url(r'^map/m(?P<id>[0-9]+)/i(?P<pk>[0-9]+)/$', inf, name='inf'),
    url(r'^map/m(?P<id>[0-9]+)/i(?P<pk>[0-9]+)/edit/$',
        csrf_exempt(edit), name='edit'),
    url(r'^map/m(?P<id>[0-9]+)/add/$', csrf_exempt(add), name='add'),
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register/', register, name='register'),
    url(r'^search/', search, name='search'),
    url(r'^lovepage/', lovepage, name='lovepage'),
    url(r'^contact/', comment, name='comment'),
    url(r'^about/', about, name='about'),
    url(r'^news/', news, name='news'),
    url(r'^$', RedirectView.as_view(url='/index/'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index , name='index'),
	url(r'^$', views.map , name='map'),
	url(r'^$', views.boothmap , name='boothmap'),
	url(r'^$', views.inf , name='inf'),
	url(r'^$', views.edit , name='edit'),
	url(r'^$', views.add , name='add'),
	url(r'^$', views.login , name='login'),
	url(r'^$', views.logout , name='logout'),
	url(r'^$', views.register , name='register'),
	url(r'^$', views.search , name='search'),
	url(r'^$', views.lovepage , name='lovepage'),
	url(r'^$', views.comment , name='comment'),
	url(r'^$', views.about , name='about'),
	url(r'^$', views.news , name='news'),
]

map/models.py
from django.db import models
from django.conf import settings
import ast
from django.contrib.auth.models import User

from .storage import OverwriteStorage
#import周家豪寫的class
def Booth_file_name(instance, filename):
    return '/'.join(['Booth', instance.event.title + '_' + instance.number])
#上面兩行為booth的相片重新命名
def Event_file_name(instance, filename):
    return '/'.join(['Event', instance.title])
#上面兩行為event的相片重新命名

class Event(models.Model):
	title = models.CharField(max_length = 150)
	desc = models.CharField(max_length = 3000)
	event_date = models.CharField(max_length = 20)
	event_address = models.CharField(max_length = 150, null=True, default=None, blank=True)
	image = models.ImageField(upload_to=Event_file_name, storage= OverwriteStorage(), null=True, default=None)
	url = models.CharField(max_length = 150, null=True, blank=True)
	#修改image的上傳地點跟格式
	def __str__(self):
		return self.title


class Booth(models.Model):
	event = models.ForeignKey(Event,on_delete = models.CASCADE)
	number = models.CharField(max_length = 5, blank=True)
	group_name = models.CharField(max_length = 150, blank=True)
	desc = models.CharField(max_length = 1000, null=True, blank=True)
	works_type = models.CharField(max_length = 150, null=True, blank=True)
	works_tag = models.CharField(max_length = 150, null=True, blank=True)
	rl = models.CharField(max_length = 150, null=True, blank=True)
	image = models.ImageField(upload_to=Booth_file_name, storage= OverwriteStorage(), null=True, default=None, blank=True)
	#修改image的上傳地點跟格式
	def __str__(self):
		return self.number

class UserProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	image = models.ImageField(upload_to ='photos', null=True, default=None, blank=True)
	point = models.IntegerField(default=0)
	def __str__(self):
		return self.user.__str__()

class User_Favorite_Booth(models.Model):
	user = models.ForeignKey(User,on_delete = models.CASCADE)
	booth = models.ForeignKey(Booth,on_delete = models.CASCADE, blank=True)
	def __str__(self):
		return '%s %s' %(self.user,self.booth)

class Comment(models.Model):
    content = models.CharField(max_length=1500)
    user = models.CharField(max_length=20)
    def __str__(self):
        return self.content

map/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.shortcuts import render
from django.contrib import auth
from .models import *
from django.db.models import Q
# Create your views here.


def index(request):
    if request.method == "POST" and 'button' in request.POST:  # 如果是以POST的方式才處理
        a = request.POST['search']

        searchevent = Booth.objects.filter(Q(desc__contains=a) | Q(group_name__contains=a) | Q(
            works_type__contains=a) | Q(works_tag__contains=a) | Q(number__contains=a)).order_by('event')
        context = {'searchevent': searchevent}
        if a:
            return render(request, "search.html", context)
    return render(request, 'index.html', locals())


def about(request):

    return render(request, 'about.html', locals())


def news(request):
    if request.method == "POST" and 'button' in request.POST:  # 如果是以POST的方式才處理
        a = request.POST['search']

        searchevent = Booth.objects.filter(Q(desc__contains=a) | Q(group_name__contains=a) | Q(
            works_type__contains=a) | Q(works_tag__contains=a) | Q(number__contains=a)).order_by('event')
        context = {'searchevent': searchevent}
        if a:
            return render(request, "search.html", context)
    return render(request, 'news.html', locals())


def map(request):
    num = Event.objects.all()
    if request.method == "POST"and 'button' in request.POST:  # 如果是以POST的方式才處理
        a = request.POST['search']

        searchevent = Booth.objects.filter(Q(desc__contains=a) | Q(group_name__contains=a) | Q(
            works_type__contains=a) | Q(works_tag__contains=a) | Q(number__contains=a)).order_by('event')
        context = {'searchevent': searchevent}
        if a:
            return render(request, "search.html", context)

    content = {'num': num}
    return render(request, 'eventlist.html', locals())


def boothmap(request, id):

    num = Event.objects.get(id=id)
    if request.method == "POST" and 'button' in request.POST:  # 如果是以POST的方式才處理
        a = request.POST['search']
        searchevent = Booth.objects.filter(Q(desc__contains=a) | Q(group_name__contains=a) | Q(
            works_type__contains=a) | Q(works_tag__contains=a) | Q(number__contains=a)).order_by('event')
        context = {'searchevent': searchevent}
        if a:
            return render(request, "search.html", context)
    if request.method == "POST" and '商業攤一' in request.POST:  # 如果是以POST的方式才處理
        boothbu1 = Booth.objects.filter(event=num, number__contains='商一')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and '商業攤二' in request.POST:  # 如果是以POST的方式才處理
        boothbu2 = Booth.objects.filter(event=num, number__contains='商二')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and '商業攤' in request.POST:  # 如果是以POST的方式才處理
        boothcw = Booth.objects.filter(event=num, number__contains='商')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'A' in request.POST:  # 如果是以POST的方式才處理
        bootha = Booth.objects.filter(event=num, number__contains='A')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'B' in request.POST:  # 如果是以POST的方式才處理
        boothb = Booth.objects.filter(event=num, number__contains='B')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'C' in request.POST:  # 如果是以POST的方式才處理
        boothc = Booth.objects.filter(event=num, number__contains='C')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'D' in request.POST:  # 如果是以POST的方式才處理
        boothd = Booth.objects.filter(event=num, number__contains='D')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'E' in request.POST:  # 如果是以POST的方式才處理
        boothe = Booth.objects.filter(event=num, number__contains='E')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'F' in request.POST:  # 如果是以POST的方式才處理
        boothf = Booth.objects.filter(event=num, number__contains='F')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'G' in request.POST:  # 如果是以POST的方式才處理
        boothg = Booth.objects.filter(event=num, number__contains='G')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'H' in request.POST:  # 如果是以POST的方式才處理
        boothh = Booth.objects.filter(event=num, number__contains='H')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'I' in request.POST:  # 如果是以POST的方式才處理
        boothi = Booth.objects.filter(event=num, number__contains='I')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'J' in request.POST:  # 如果是以POST的方式才處理
        boothj = Booth.objects.filter(event=num, number__contains='J')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'K' in request.POST:  # 如果是以POST的方式才處理
        boothk = Booth.objects.filter(event=num, number__contains='K')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'L' in request.POST:  # 如果是以POST的方式才處理
        boothl = Booth.objects.filter(event=num, number__contains='L')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'M' in request.POST:  # 如果是以POST的方式才處理
        boothm = Booth.objects.filter(event=num, number__contains='M')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'N' in request.POST:  # 如果是以POST的方式才處理
        boothn = Booth.objects.filter(event=num, number__contains='N')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'O' in request.POST:  # 如果是以POST的方式才處理
        bootho = Booth.objects.filter(event=num, number__contains='O')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'P' in request.POST:  # 如果是以POST的方式才處理
        boothp = Booth.objects.filter(event=num, number__contains='P')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'Q' in request.POST:  # 如果是以POST的方式才處理
        boothq = Booth.objects.filter(event=num, number__contains='Q')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'R' in request.POST:  # 如果是以POST的方式才處理
        boothr = Booth.objects.filter(event=num, number__contains='R')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'S' in request.POST:  # 如果是以POST的方式才處理
        booths = Booth.objects.filter(event=num, number__contains='S')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'T' in request.POST:  # 如果是以POST的方式才處理
        bootht = Booth.objects.filter(event=num, number__contains='T')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'U' in request.POST:  # 如果是以POST的方式才處理
        boothu = Booth.objects.filter(event=num, number__contains='U')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'V' in request.POST:  # 如果是以POST的方式才處理
        boothv = Booth.objects.filter(event=num, number__contains='V')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'W' in request.POST:  # 如果是以POST的方式才處理
        boothw = Booth.objects.filter(event=num, number__contains='W')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'X' in request.POST:  # 如果是以POST的方式才處理
        boothx = Booth.objects.filter(event=num, number__contains='X')
        return render(request, "areamap.html", locals())
    if request.method == "POST" and 'Y' in request.POST:  # 如果是以POST的方式才處理
        boothy = Booth.objects.filter(event=num, number__contains='Y')
        return render(request, "areamap.html", locals())

    return render(request, 'map.html', locals())


def inf(request, id, pk):
    if request.method == "POST"and 'button' in request.POST:  # 如果是以POST的方式才處理
        a = request.POST['search']

        searchevent = Booth.objects.filter(Q(desc__contains=a) | Q(group_name__contains=a) | Q(
            works_type__contains=a) | Q(works_tag__contains=a) | Q(number__contains=a)).order_by('event')
        context = {'searchevent': searchevent}
        if a:
            return render(request, "search.html", context)
    num = Event.objects.get(id=id)
    boothpk = Booth.objects.get(pk=pk)
    if request.user.is_authenticated:
        user = User.objects.get(id=request.user.id)
        love = User_Favorite_Booth.objects.filter(user=user, booth=boothpk)
    if request.method == "POST":  # 如果是以POST的方式才處理
        if User_Favorite_Booth.objects.filter(user=user, booth=boothpk):
            User_Favorite_Booth.objects.filter(
                user=user, booth=boothpk).delete()
        else:
            User_Favorite_Booth.objects.create(user=user, booth=boothpk)
        return render(request, 'information.html', locals())

    return render(request, 'information.html', locals())


@login_required
def edit(request, id, pk):

    num = Event.objects.get(id=id)
    boothpk = Booth.objects.get(pk=pk)

    if request.method == "POST":  # 如果是以POST的方式才處理

        boothpk.desc = request.POST['desc']
        boothpk.works_type = request.POST['workstype']
        boothpk.works_tag = request.POST['workstag']
        boothpk.rl = request.POST['url']
        #boothpk.image = request.FILES.get('ismage')
        image = request.FILES.get('image')
        if image != None:

map/templates/about.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE HTML>

<html>
<head>
	<title>BOOTH GO! about us</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="is-preload">
	<div id="page-wrapper">

		<!-- Header -->
    <div id="header" >  
      <!--FB..
      <div id="top">
        <ul class="community">
          <li><a target="_blank" class="fb">facebook</a></li>
          <li><a target="_blank" class="ig">IG</a></li>
        </ul>
      </div>-->

      

      <!-- Nav -->
      <div id="nav">
        <!-- Logo -->
        <h1>
          <a id="logo" class="font-white" href="/index" >BOOTH GO! </a>
        </h1>
        {% if request.user.is_authenticated %}
			<p id="Hello" >Hello, {{ user.username }}.
		{% endif %}
        <ul>
          <li><a href="/index">Home</a></li>
          	{% if request.user.is_authenticated %}
			    <li><a href="/logout">Logout</a></li>
			{% else %}
			    <li><a href="/login">Login</a></li>
			{% endif %}
          <li class="current"><a href="/about">About us</a></li>
          <li ><a href="/contact">Contact us</a></li>
          <li><a>more</a>
            <ul>
              <li><a href="/map">展覽活動</a></li>
              <li><a href="/news">最新消息</a></li>
              <li><a href="/lovepage">我的最愛</a></li>
            </ul>
          </li>
        </ul>
        <!--search-->
				<div class="box1">
					
					<form method="POST" name="form1" >   <!-- 建立form表單，設定傳送方式為GET，「action="/edit/{{unit.id}}/edit"」中第三個參數為edit，表示他是從<edit.html>按送出鈕傳送過來的-->

                    {% csrf_token %}     <!-- #CSRF防護請加在此 -->
                    	<table border="1" cellpadding="1" cellspacing="4">
                        
    						<!-- #CSRF防護請加在此 -->
                    		
	                            <input type="text" id="search" name="search" placeholder="Type...">
	                 
	                            <input type="submit" name="button" id="button" value="Search">

                        
                    </table>

                   
                </form> 
  					
  				</div>
  				<!--search end-->
      </div>
    </div>
		<!-- Main -->
		<section class="wrapper style1">
			<div id="container">
				<div class="row gtr-200">
					<div class="col-12">
						<div class="container1">

							<!-- Content -->

							<article>
								<header>
									<a style="font-size: 30px; font-weight: 600; color: black;border: 0;">BOOTH GO!</a>
								</header>

								<span class="image featured"><img src="images/banner.jpg" alt="" /></span>

								<p>我們是第八組呦!</p>
								<br>
								<p style="display: table-cell;vertical-align: middle;">
								以現代的角度來看，「逛展」這件事是有點麻煩甚至是浪費時間，畢竟在資訊發達的現在，沒有什麼事是網路搜尋不能解決的；如果有，發文問問題也能快速解決；但也因為網路的便利性，導致人們逐漸依賴網路，認為google一下有看過就好，並沒有實際去看過、碰過那些事物。</p>
								<br>
								<p style="display: table-cell;vertical-align: middle;">
								展覽讓參加者們能真的去觀賞、觸碰那些他們只在網路上看過的東西；然而現代的展覽有個問題⸺資訊十分的分散以及不流通，往往展覽的主辦方只會提供攤位地圖以及攤位名稱，無法實際了解該攤位主打的特色或是有在販賣的商品，只能透過參加者們自行上網搜尋以後才能得知。即使是資訊展和書展這種參展者資訊非常容易查找、攤位數也不會過多的展覽都會讓想參展的人感到些微不耐煩，屬於同好販售活動的開拓動漫祭（FF）、台灣同人誌販售（C.W.T）… …等，每一次活動都有上百快破千的攤位數，除了事前已經就知道的參展者外，對於其他參展者的理解並不完全。這種情況下還要再慢慢搜尋資訊，不但參加活動的熱情會消退還很容易發生「沒搜尋到而錯過作品」的遺憾。
								</p>
								<br>
								<p style="display: table-cell;vertical-align: middle;">
									所以我們想解決這一問題，來達到資訊在參加者們互相流通，除了解決原本資訊不全以外，我們希望能透過參加者的力量，來讓攤位的資訊變得更加齊全，這樣不僅參加者自身查詢方便，同時讓參展者們能更有效率的來推銷自己的產品。
								</p>
							</article>

						</div>
						
					</div>
				</div>
			</div>
		</section>
	</div>

	<!--footer2-->
		<div id="footer2">
			<div class="footer2-content">
				<!--
				<img src="upload/15222185171718.jpg" width="100" alt="QRCODE" class="qr-code">
				-->
				<ul class="footer2-nav">
					<li class="font-white">相關連結</li>
					<li><a href="https://www.tainex1.com.tw/zh-tw/">南港展覽館</a></li>
					<li><a href="http://www.twtc.org.tw/index.aspx">世貿展覽館</a></li>
					<li><a href="index">台大體育館</a></li>
				</ul>
			</div>
		</div>
		<!--footer end-->

</div>

			<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
				<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
				<script src="{% static 'js/browser.min.js' %}"></script>
				<script src="{% static 'js/breakpoints.min.js' %}"></script>
				<script src="{% static 'js/util.js' %}"></script>
				<script src="{% static 'js/main.js' %}"></script>
				<script src="{% static 'js/slide.js' %}"></script>

		</body>
		</html>

map/templates/add.html
<!DOCTYPE html>
<html>

    <head>
        
    </head>
    <body>
       <form method="POST" name="form1">   <!-- 建立form表單，設定傳送方式為GET，「action="/edit/{{unit.id}}/edit"」中第三個參數為edit，表示他是從<edit.html>按送出鈕傳送過來的-->

        {% csrf_token %}     <!-- #CSRF防護請加在此 -->
        <table border="1" cellpadding="1" cellspacing="4">
            <tr>
                <th>社團編號</th>
                <td><input type="text" id="number" name="number"></td>
            </tr>
            <tr>
                <th>社團名稱</th>
                <td><input type="text" id="groupname" name="groupname"></td>
            </tr>
            <tr>
                <th>描述</th>
                <td><input type="text" id="desc" name="desc" ></td>
            </tr>
            <tr>
                <th>類型</th>
                <td><input type="text" id="worktype" name="workstype"></td>
            </tr>
            <tr>
                <th>Tag</th>
                <td><input type="text" id="worktag" name="workstag" ></td>
            </tr>
            <tr>
                <th>picture</th>
                <td><input type="file" name="filename" value=""></td>
            </tr>
            <tr>
                <th colspan="2" align="center">
                    <input type="submit" name="button" id="button" value="送出">
                    <input type="reset" name="button2" id="button2" value="重設">
            </tr>
        </table>
        
    </form> 
    

    {% for n in num.booth_set.all %}
        {{ forloop.counter }}
    {% endfor %}
    
    </body>
</html>

map/templates/contact.html
{% load static %}
{% load staticfiles %}
{% block title %}
<meta charset="utf-8">
<title>給我們建議吧</title>
{% endblock %}

<!DOCTYPE HTML>
<!--
    Arcana by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>活動攤位整合平臺contact us</title>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="is-preload">
    <div id="page-wrapper">

        <!-- Header -->
        <div id="header" >  
        <!--FB..
      <div id="top">
        <ul class="community">
          <li><a target="_blank" class="fb">facebook</a></li>
          <li><a target="_blank" class="ig">IG</a></li>
        </ul>
      </div>-->

      

      <!-- Nav -->
        <div id="nav">
        <!-- Logo -->
        <h1><a href="/index" id="logo">BOOTH GO!<em></em></a></h1>
        {% if request.user.is_authenticated %}
            <p id="Hello" >Hello, {{ user.username }}.
        {% endif %}
        <ul>
          <li><a href="/index">Home</a></li>

            <li><a href="/logout">Logout</a></li>

          <li><a href="/about">About us</a></li>
          <li class="current"><a href="/contact">Contact us</a></li>
          <li><a>more</a>
            <ul>
              <li><a href="/map">展覽活動</a></li>
              <li><a href="/news">最新消息</a></li>
              <li><a href="/lovepage">我的最愛</a></li>
            </ul>
          </li>
        </ul>
        <!--search-->
                
                <!--search end-->
      </div>
    </div>
    
<div id="container">
    <!-- Main -->
    <section class="wrapper style1">
        <div class="container1">
                <!-- Content -->

                <article>
                    <header>
                        <h2>感謝回饋</h2>
                        <p>Thank you for your suggestion.</p>
                    </header>
                </article>


                <!-- Footer1 -->
                <div id="footer1">
                        <div class="row">
                            <section class="col-12">
                                <form>
                                    <div class="row gtr-50">
                                        <form method="POST" name="form1"> 
                                            {% csrf_token %} 
                                        <div class="col-12">
                                            <textarea name="message" id="message" placeholder="Suggestion" rows="5"></textarea>

                                        </div>
                                        <div class="col-12">
                                            <ul class="actions">
                                                <li><input type="submit" class="button alt" name="button" id="button" value="Send Message"></li>
                                            </ul>
                                        </div>
                                            </form> 
                                    </div>
                                </form>
                            </section>
                        </div>
                </div>
        </div>
    </section>
</div>

    <!--footer2-->
        <div id="footer2">
            <div class="footer2-content">
                <!--
                <img src="upload/15222185171718.jpg" width="100" alt="QRCODE" class="qr-code">
                -->
                <ul class="footer2-nav">
                    <li class="font-white">相關連結</li>
                    <li><a href="https://www.tainex1.com.tw/zh-tw/">南港展覽館</a></li>
                    <li><a href="http://www.twtc.org.tw/index.aspx">世貿展覽館</a></li>
                    <li><a href="index">台大體育館</a></li>
                </ul>
            </div>
        </div>
        <!--footer end-->
    
</div>

        <!-- Scripts -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
        <script src="{% static 'js/browser.min.js' %}"></script>
        <script src="{% static 'js/breakpoints.min.js' %}"></script>
        <script src="{% static 'js/util.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

    </body>
    </html>




    